// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (!(window.fw != null)) {
    window.fw = {};
  }

  (function($) {
    return window.fw.BaseScroller = (function() {
      var baseOptions;

      baseOptions = {
        scrollStep: 150,
        offset: 0,
        mousewheel: true,
        scrollbar: true,
        scrollerSelector: '[data-scroller=scroller]',
        contentSelector: '[data-scroller=content]',
        innerContentSelector: '[data-scroller=innercontent]',
        previousSelector: '[data-scroller=previous]',
        nextSelector: '[data-scroller=next]',
        draggerContainerSelector: '[data-scroller=dragger-container]',
        draggerSelector: '[data-scroller=dragger]',
        scrollerStyles: {
          position: 'relative',
          top: 0,
          left: 0,
          overflow: 'hidden'
        },
        contentStyles: {
          position: 'absolute',
          top: 0,
          left: 0
        },
        draggerContainerStyles: {
          position: 'relative',
          top: 0,
          left: 0
        },
        draggerStyles: {
          position: 'absolute',
          top: 0,
          left: 0,
          'max-width': '100%',
          'max-height': '100%'
        },
        animateOptions: {
          duration: 500
        }
      };

      function BaseScroller(container, options) {
        if (options == null) {
          options = {};
        }
        this.options = $.extend({}, baseOptions, options);
        this.currentPos = 0;
        this.$container = $(container);
        this.$scroller = this.$container.find(this.options.scrollerSelector);
        this.$content = this.$scroller.find(this.options.contentSelector);
        this.$innerContent = this.$content.find(this.options.innerContentSelector);
        this.$scroller.css(this.options.scrollerStyles);
        this.$content.css(this.options.contentStyles);
        this.$container.delegate(this.options.previousSelector, 'click', this.previous.bind(this, 1));
        this.$container.delegate(this.options.nextSelector, 'click', this.next.bind(this, 1));
        if (this.options.mousewheel) {
          this.$container.bind('mousewheel', this.onMousewheel.bind(this));
        }
      }

      BaseScroller.prototype.initScrollbar = function() {
        this.$draggerContainer = this.$container.find(this.options.draggerContainerSelector);
        this.$dragger = this.$draggerContainer.find(this.options.draggerSelector);
        this.scrollbarSize = Math.round((this.scrollerSize / this.contentSize) * 100);
        return this.$draggerContainer.css(this.options.draggerContainerStyles);
      };

      BaseScroller.prototype.slideTo = function(pos, triggerEvent, animate) {
        if (triggerEvent == null) {
          triggerEvent = true;
        }
        if (animate == null) {
          animate = true;
        }
        if (pos > this.maxPos) {
          pos = this.maxPos;
        }
        if (pos < 0) {
          pos = 0;
        }
        this.currentPos = pos;
        if (triggerEvent) {
          return $(this).trigger('slide');
        }
      };

      BaseScroller.prototype.next = function(offset) {
        if (offset == null) {
          offset = 1;
        }
        return this.slideTo(this.currentPos + this.options.scrollStep * offset);
      };

      BaseScroller.prototype.previous = function(offset) {
        if (offset == null) {
          offset = 1;
        }
        return this.slideTo(this.currentPos - this.options.scrollStep * offset);
      };

      BaseScroller.prototype.onMousewheel = function(event, delta) {
        this[delta < 0 ? 'previous' : 'next'](Math.abs(delta));
        return false;
      };

      return BaseScroller;

    })();
  })(jQuery);

  if (!(window.fw != null)) {
    window.fw = {};
  }

  (function($) {
    return window.fw.HorizontalScroller = (function(_super) {
      var baseOptions;

      __extends(HorizontalScroller, _super);

      baseOptions = {
        scrollStep: 25,
        draggerStyles: {
          position: 'absolute',
          top: 0,
          left: 0,
          'max-width': '100%'
        }
      };

      function HorizontalScroller(container, options) {
        if (options == null) {
          options = {};
        }
        HorizontalScroller.__super__.constructor.call(this, container, $.extend({}, baseOptions, options));
        this.$content.width('999999px');
        this.contentSize = this.$innerContent.width() + this.options.offset;
        this.$content.width(this.contentSize);
        this.scrollerSize = this.$scroller.width();
        this.maxPos = this.contentSize - this.scrollerSize;
        if (this.options.scrollbar) {
          this.initScrollbar();
        }
      }

      HorizontalScroller.prototype.initScrollbar = function() {
        var _this = this;
        HorizontalScroller.__super__.initScrollbar.call(this);
        this.$dragger.css($.extend({}, this.options.draggerStyles, {
          width: this.scrollbarSize + '%'
        }));
        this.$dragger.draggable({
          axis: 'x',
          containment: this.$draggerContainer,
          drag: function(event, ui) {
            return _this.slideTo((ui.position.left / _this.$draggerContainer.width()) * _this.contentSize, false, false);
          }
        });
        return $(this).bind('slide', function() {
          return _this.$dragger.stop().animate({
            left: (_this.currentPos / _this.contentSize) * 100 + '%'
          }, _this.options.animateOptions);
        });
      };

      HorizontalScroller.prototype.slideTo = function(pos, triggerEvent, animate) {
        if (triggerEvent == null) {
          triggerEvent = true;
        }
        if (animate == null) {
          animate = true;
        }
        HorizontalScroller.__super__.slideTo.call(this, pos, triggerEvent, animate);
        if (animate) {
          return this.$content.stop().animate({
            left: (-this.currentPos) + 'px'
          }, this.options.animateOptions);
        } else {
          return this.$content.css({
            left: (-this.currentPos) + 'px'
          });
        }
      };

      return HorizontalScroller;

    })(window.fw.BaseScroller);
  })(jQuery);

  (function($) {
    return $.fn.scroller = function(option) {
      var args;
      args = arguments;
      return this.each(function() {
        var $this, data;
        $this = $(this);
        data = $this.data('fw.scroller');
        if (!(data != null)) {
          if ($this.attr('data-scroller') === 'horizontal' || ((option != null) && (option.horizontal != null) && option.horizontal)) {
            $this.data('fw.scroller', data = new window.fw.HorizontalScroller($this, option));
          } else {
            $this.data('fw.scroller', data = new window.fw.VerticalScroller($this, option));
          }
        }
        if (data && typeof option === 'string' && typeof data[option] === 'function') {
          return data[option].apply(data, [].slice.call(args, 1));
        }
      });
    };
  })(jQuery);

  if (!(window.fw != null)) {
    window.fw = {};
  }

  (function($) {
    return window.fw.VerticalScroller = (function(_super) {
      var baseOptions;

      __extends(VerticalScroller, _super);

      baseOptions = {
        scrollStep: 25,
        draggerStyles: {
          position: 'absolute',
          top: 0,
          left: 0,
          'max-height': '100%'
        }
      };

      function VerticalScroller(container, options) {
        if (options == null) {
          options = {};
        }
        VerticalScroller.__super__.constructor.call(this, container, $.extend({}, baseOptions, options));
        this.$content.height('999999px');
        this.contentSize = this.$innerContent.height() + this.options.offset;
        this.$content.height(this.contentSize);
        this.scrollerSize = this.$scroller.height();
        this.maxPos = this.contentSize - this.scrollerSize;
        if (this.options.scrollbar) {
          this.initScrollbar();
        }
      }

      VerticalScroller.prototype.initScrollbar = function() {
        var _this = this;
        VerticalScroller.__super__.initScrollbar.call(this);
        this.$dragger.css($.extend({}, this.options.draggerStyles, {
          height: this.scrollbarSize + '%'
        }));
        this.$dragger.draggable({
          axis: 'y',
          containment: this.$draggerContainer,
          drag: function(event, ui) {
            return _this.slideTo((ui.position.top / _this.$draggerContainer.height()) * _this.contentSize, false, false);
          }
        });
        return $(this).bind('slide', function() {
          return _this.$dragger.stop().animate({
            top: (_this.currentPos / _this.contentSize) * 100 + '%'
          }, _this.options.animateOptions);
        });
      };

      VerticalScroller.prototype.slideTo = function(pos, triggerEvent, animate) {
        if (triggerEvent == null) {
          triggerEvent = true;
        }
        if (animate == null) {
          animate = true;
        }
        VerticalScroller.__super__.slideTo.call(this, pos, triggerEvent, animate);
        if (animate) {
          return this.$content.stop().animate({
            top: (-this.currentPos) + 'px'
          }, this.options.animateOptions);
        } else {
          return this.$content.css({
            top: (-this.currentPos) + 'px'
          });
        }
      };

      return VerticalScroller;

    })(window.fw.BaseScroller);
  })(jQuery);

}).call(this);
